# Generated by Django 5.1.15 on 2026-06-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='На головній'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='product_type',
            field=models.CharField(default='Extrait de Parfum', max_length=80, verbose_name='Тип продукту'),
        ),
    ]
